export enum FormProperties {
  Appearance = 'appearance',
  Classes = 'classes',
  Color = 'color',
  Hint = 'hint',
  Indeterminate = 'indeterminate',
  Label = 'label',
  LabelPosition = 'labelPosition',
  Name = 'name',
  Placeholder = 'placeholder',
  PrefixType = 'prefix.type',
  PrefixValue = 'prefix.value',
  Required = 'required',
  RequiredMsg = 'requiredMsg',
  Options = 'options',
  ShowInline = 'showInline',
  Submit = '_submit_',
  SubType = 'subType',
  SuffixType = 'suffix.type',
  SuffixValue = 'suffix.value',
  Value = 'value',
}